[package]
name = "todo-backend"
version = "0.1.0"
edition = "2018"
authors = ["Nicholas Salesky <nicksalesky@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"